name: notepad
description: "A simple personal Notepad app using Flutter with local storage."
publish_to: 'none' # This app is private, remove this if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Enhancements
  cupertino_icons: ^1.0.8
  get: ^4.7.2

  # Local Database (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Sharing Feature
  share_plus: ^10.1.4

  # HTTP Requests (Future API Integrations)
  http: ^1.3.0

  # Splash Screen
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_test: ^1.0.1
  mockito: ^5.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/splash_icon.png # Added splash screen image

  # Fonts Configuration (Optional)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
