on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop  

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest  # Change this to ubuntu-latest if you only want Android builds
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fixed reference

      - name: Setup Java
        uses: actions/setup-java@v1
        with: 
          distribution: 'temurin'
          java-version: '12'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2  # Updated to latest
        with:
          flutter-version: '3.29.1'  # You can also use stable instead of a fixed version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --debug --split-per-abi  

      - name: Push to Releases
        uses: ncipollo/release-action@v1  
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
